"use client";

import { useState } from "react";
import Link from "next/link";

interface DemoStep {
  id: number;
  title: string;
  description: string;
  repoId: string;
  path: string;
  icon: string;
  details: string[];
}

const DEMO_STEPS: DemoStep[] = [
  {
    id: 1,
    title: "Explore the Architecture Map",
    description:
      "See the full system architecture of an Express.js e-commerce API — modules, dependencies, and tech stack — all auto-generated by AI.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop",
    icon: "🏗️",
    details: [
      "React Flow interactive node graph",
      "7 modules detected: API Gateway, Auth, Products, Orders, Payments, Database, Cache",
      "Dependency edges show data flow between modules",
      "Tech stack breakdown (Express, Prisma, PostgreSQL, Redis, Stripe)",
    ],
  },
  {
    id: 2,
    title: "Watch Animated Data Flows",
    description:
      "Step through an animated visualization of how an order is processed — from cart checkout through Stripe payment to webhook confirmation.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/animated",
    icon: "🎬",
    details: [
      "3 pre-built animation sequences (Auth, Order, Data Pipeline)",
      "Click any node for an AI-generated plain-English explanation",
      "Multi-language support: Hindi, Tamil, Telugu, Kannada, Bengali, Marathi",
      "Fresher-friendly mode for beginners",
    ],
  },
  {
    id: 3,
    title: "Read Code Walkthroughs",
    description:
      "Follow AI-generated step-by-step walkthroughs of key features like authentication and order processing, linked to actual source files.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/walkthroughs",
    icon: "📖",
    details: [
      "Pre-built walkthroughs: JWT Auth Flow, Order Pipeline, Database Schema",
      "Each step references specific files and line ranges",
      "Ask a custom question to generate a new walkthrough on the fly",
      "Great for onboarding new team members",
    ],
  },
  {
    id: 4,
    title: "Ask Questions (AI Q&A)",
    description:
      "Ask natural language questions about the codebase and get context-aware answers with relevant file references and follow-up suggestions.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/qa",
    icon: "💬",
    details: [
      'Try: "How does authentication work?"',
      'Try: "How are orders processed?"',
      'Try: "What is the database schema?"',
      "Answers include relevant files and related question suggestions",
    ],
  },
  {
    id: 5,
    title: "Track Team Progress",
    description:
      "See how team members are progressing through onboarding — skill radars, timelines, leaderboard, and module completion grids.",
    repoId: "demo/express-shop",
    path: "/dashboard/demo%2Fexpress-shop/team",
    icon: "📊",
    details: [
      "3 team members with different progress levels",
      "Skill radar chart showing per-area competency",
      "Leaderboard with medals and time tracking",
      "Individual progress timelines",
    ],
  },
];

export default function DemoScriptPage() {
  const [activeStep, setActiveStep] = useState(0);

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950 text-white">
      {/* Header */}
      <header className="border-b border-gray-800 bg-gray-950/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent"
            >
              AutoDev
            </Link>
            <span className="text-xs px-2.5 py-1 rounded-full bg-purple-900/50 text-purple-300 border border-purple-700/50">
              Demo Script
            </span>
          </div>
          <Link
            href="/dashboard?demo=true"
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg text-sm font-medium transition-colors"
          >
            Open Dashboard →
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-6xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-4">
          AutoDev Demo Walkthrough
        </h1>
        <p className="text-gray-400 text-lg max-w-2xl mb-2">
          Follow this 5-step guided demo to see how AutoDev transforms codebase
          onboarding. Each step links directly to a live demo page with
          pre-analyzed data — no AWS credentials required.
        </p>
        <p className="text-gray-500 text-sm">
          AI for Bharat Hackathon 2026 · Student Track · Team AutoDev
        </p>
      </section>

      {/* Steps */}
      <section className="max-w-6xl mx-auto px-6 pb-20">
        <div className="grid gap-6">
          {DEMO_STEPS.map((step, index) => {
            const isActive = activeStep === index;

            return (
              <div
                key={step.id}
                className={`border rounded-xl transition-all duration-300 ${
                  isActive
                    ? "border-blue-500/50 bg-gray-900/80 shadow-lg shadow-blue-500/10"
                    : "border-gray-800 bg-gray-900/30 hover:border-gray-700"
                }`}
              >
                <button
                  onClick={() => setActiveStep(isActive ? -1 : index)}
                  className="w-full text-left p-6 flex items-start gap-5"
                >
                  {/* Step number */}
                  <div
                    className={`flex-shrink-0 w-12 h-12 rounded-xl flex items-center justify-center text-2xl ${
                      isActive
                        ? "bg-blue-600/20 border border-blue-500/30"
                        : "bg-gray-800/50"
                    }`}
                  >
                    {step.icon}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-1">
                      <span className="text-xs text-gray-500 font-mono">
                        Step {step.id}/5
                      </span>
                    </div>
                    <h3 className="text-lg font-semibold mb-1">{step.title}</h3>
                    <p className="text-gray-400 text-sm">{step.description}</p>
                  </div>

                  {/* Chevron */}
                  <svg
                    className={`w-5 h-5 text-gray-500 transition-transform flex-shrink-0 mt-1 ${
                      isActive ? "rotate-180" : ""
                    }`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                </button>

                {/* Expanded details */}
                {isActive && (
                  <div className="px-6 pb-6 pt-0">
                    <div className="ml-17 pl-17">
                      <div className="border-t border-gray-800 pt-4 ml-[4.25rem]">
                        <h4 className="text-sm font-medium text-gray-300 mb-3">
                          What you&apos;ll see:
                        </h4>
                        <ul className="space-y-2 mb-5">
                          {step.details.map((detail, i) => (
                            <li
                              key={i}
                              className="flex items-start gap-2 text-sm text-gray-400"
                            >
                              <span className="text-blue-400 mt-0.5">•</span>
                              {detail}
                            </li>
                          ))}
                        </ul>
                        <Link
                          href={step.path}
                          className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg text-sm font-medium transition-colors"
                        >
                          Open Step {step.id} →
                        </Link>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Also explore */}
        <div className="mt-12 p-6 border border-gray-800 rounded-xl bg-gray-900/30">
          <h3 className="text-lg font-semibold mb-3">Also Explore</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Link
              href="/dashboard/demo%2Fexpress-shop/conventions"
              className="p-4 border border-gray-800 rounded-lg hover:border-gray-700 transition-colors"
            >
              <p className="font-medium text-sm">📋 Coding Conventions</p>
              <p className="text-gray-500 text-xs mt-1">
                AI-detected naming, structure, and error handling patterns
              </p>
            </Link>
            <Link
              href="/dashboard/demo%2Fexpress-shop/env-setup"
              className="p-4 border border-gray-800 rounded-lg hover:border-gray-700 transition-colors"
            >
              <p className="font-medium text-sm">⚙️ Env Setup Guide</p>
              <p className="text-gray-500 text-xs mt-1">
                Auto-generated prerequisites, install steps, and verification
              </p>
            </Link>
            <Link
              href="/dashboard/demo%2Fexpress-shop/progress"
              className="p-4 border border-gray-800 rounded-lg hover:border-gray-700 transition-colors"
            >
              <p className="font-medium text-sm">📈 My Progress</p>
              <p className="text-gray-500 text-xs mt-1">
                Skill radar, timeline, and module completion tracking
              </p>
            </Link>
          </div>
        </div>

        {/* Other demo repos */}
        <div className="mt-8 p-6 border border-gray-800 rounded-xl bg-gray-900/30">
          <h3 className="text-lg font-semibold mb-3">Try Other Demo Repos</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Link
              href="/dashboard/demo%2Freact-dashboard"
              className="p-4 border border-gray-800 rounded-lg hover:border-gray-700 transition-colors"
            >
              <p className="font-medium text-sm">⚛️ React Dashboard</p>
              <p className="text-gray-500 text-xs mt-1">
                Next.js 14 + Supabase + Tailwind CSS (134 files)
              </p>
            </Link>
            <Link
              href="/dashboard/demo%2Fpython-ml-api"
              className="p-4 border border-gray-800 rounded-lg hover:border-gray-700 transition-colors"
            >
              <p className="font-medium text-sm">🐍 Python ML API</p>
              <p className="text-gray-500 text-xs mt-1">
                FastAPI + MongoDB + scikit-learn (52 files)
              </p>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
