import type { Context } from "probot";

const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:3001";

export async function handlePullRequest(
  context: Context<"pull_request.opened"> | Context<"pull_request.synchronize">
) {
  const { pull_request, repository } = context.payload;
  const repoFullName = repository.full_name;

  context.log.info(
    `PR #${pull_request.number} on ${repoFullName}: ${pull_request.title}`
  );

  try {
    // Fetch the changed files in this PR
    const filesRes = await context.octokit.pulls.listFiles(
      context.pullRequest({ per_page: 100 })
    );
    const changedFiles = filesRes.data.map((f) => f.filename);

    // Fetch architecture analysis from backend
    const [owner, repo] = repoFullName.split("/");
    let architecture: Record<string, unknown> | null = null;
    try {
      const archRes = await fetch(
        `${BACKEND_URL}/api/analysis/${owner}/${repo}/architecture`
      );
      if (archRes.ok) {
        const data = (await archRes.json()) as Record<string, unknown>;
        architecture = data;
      }
    } catch {
      context.log.warn(`Could not fetch architecture for ${repoFullName}`);
    }

    // Fetch conventions
    let conventions: Array<{ category: string; pattern: string; description: string }> = [];
    try {
      const convRes = await fetch(
        `${BACKEND_URL}/api/conventions/${owner}/${repo}`
      );
      if (convRes.ok) {
        const data = (await convRes.json()) as {
          conventions: Array<{ category: string; pattern: string; description: string }>;
        };
        conventions = data.conventions || [];
      }
    } catch {
      context.log.warn(`Could not fetch conventions for ${repoFullName}`);
    }

    // Build the onboarding impact comment
    const sections: string[] = [];
    sections.push("## 🗺️ AutoDev Onboarding Context\n");

    // Identify affected modules from architecture
    if (architecture) {
      const nodes = (architecture as Record<string, unknown>).nodes as
        | Array<{ label: string; files: string[]; description: string }>
        | undefined;
      if (nodes) {
        const affectedModules = nodes.filter((node) =>
          node.files?.some((file) =>
            changedFiles.some(
              (cf) => cf === file || cf.startsWith(file.replace(/\/[^/]+$/, "/"))
            )
          )
        );
        if (affectedModules.length > 0) {
          sections.push("### Affected Modules\n");
          for (const mod of affectedModules) {
            sections.push(`- **${mod.label}**: ${mod.description}`);
          }
          sections.push("");
        }
      }
    }

    // Show changed files grouped by type
    sections.push(`### Changed Files (${changedFiles.length})\n`);
    const filesByDir: Record<string, string[]> = {};
    for (const f of changedFiles) {
      const dir = f.includes("/") ? f.split("/").slice(0, -1).join("/") : ".";
      (filesByDir[dir] ??= []).push(f.split("/").pop() || f);
    }
    for (const [dir, files] of Object.entries(filesByDir).slice(0, 10)) {
      sections.push(`- \`${dir}/\`: ${files.join(", ")}`);
    }
    sections.push("");

    // Show relevant conventions
    if (conventions.length > 0) {
      sections.push("### Relevant Conventions\n");
      const relevantConventions = conventions.slice(0, 5);
      for (const conv of relevantConventions) {
        sections.push(
          `- **${conv.category}** — \`${conv.pattern}\`: ${conv.description}`
        );
      }
      sections.push("");
    }

    sections.push(
      `\n> 💡 [View full architecture & walkthroughs](${BACKEND_URL})\n`
    );
    sections.push("*Generated by AutoDev — AI-powered codebase onboarding*");

    const body = sections.join("\n");

    // Post the comment on the PR
    await context.octokit.issues.createComment(
      context.issue({ body })
    );

    context.log.info(
      `Posted onboarding context comment on PR #${pull_request.number}`
    );
  } catch (error) {
    context.log.error(
      `Failed to generate onboarding context for PR #${pull_request.number}:`,
      error as Error
    );
  }
}
